/**
 * Meetings Mode 3 — Post-Meeting Executive Summary, Decision Log & Action Items View
 * Decision Log Cards, Extracted Action Items with 1-click Convert to Task, and Recording Player.
 */

export function renderModeSummary(mtg) {
  return `
    <div style="padding-top:var(--s-6);display:flex;flex-direction:column;gap:var(--s-6)">
      <!-- Top Bar -->
      <div class="dash-card">
        <div style="display:flex;align-items:flex-start;justify-content:space-between">
          <div style="display:flex;align-items:center;gap:var(--s-4)">
            <button class="task-act-btn" id="back-to-meetings-home-btn-2">← All Meetings</button>
            <div>
              <div style="display:flex;align-items:center;gap:8px">
                <span class="project-status-badge" style="background:#22c55e22;color:#22c55e;border:1px solid #22c55e44">● COMPLETED SUMMARY</span>
                <h1 style="font-size:var(--fs-2xl);font-weight:800;color:var(--text-1)">${mtg.title}</h1>
              </div>
              <div style="font-size:13px;color:var(--text-3);margin-top:4px">${mtg.time} (${mtg.duration}) • Host: ${mtg.organizer.name}</div>
            </div>
          </div>

          <button class="top-nav-btn primary-create" id="export-recap-email-btn" style="height:36px;font-size:12px">
            <span>✉️ Export Email Recap</span>
          </button>
        </div>
      </div>

      <div class="dashboard-grid-12">
        <!-- Left Column (8 Cols): Executive AI Summary & Decision Log -->
        <div class="col-span-8" style="display:flex;flex-direction:column;gap:var(--s-6)">
          <!-- Executive AI Summary -->
          <div class="dash-card ai-brief-card">
            <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:var(--s-3)">
              <div class="ai-header-badge">
                <span>✨ Automated Executive AI Summary</span>
              </div>
              <span style="font-size:12px;color:var(--e-400);font-weight:600">● 99% AI Confidence</span>
            </div>

            <div class="ai-summary-box">
              ${mtg.executiveSummary || 'Executive summary generated by Nova AI Assistant from meeting recording.'}
            </div>
          </div>

          <!-- Decision Log Cards -->
          <div class="dash-card">
            <div class="card-header-flex">
              <div class="card-title-group">
                <div class="ws-icon-box" style="background:rgba(110,74,255,0.15);color:#6e4aff">⚖️</div>
                <div>
                  <h2 class="card-title">Decision Log (${mtg.decisions ? mtg.decisions.length : 0})</h2>
                  <div class="card-subtitle">Formal organizational decisions recorded during sync</div>
                </div>
              </div>
            </div>

            <div style="display:flex;flex-direction:column;gap:var(--s-3)">
              ${mtg.decisions ? mtg.decisions.map(dec => `
                <div class="decision-card-item">
                  <div style="display:flex;align-items:center;justify-content:space-between">
                    <span style="font-size:15px;font-weight:700;color:var(--text-1)">${dec.title}</span>
                    <span class="auth-preview-pill pill-violet" style="font-size:10px">${dec.impact} Impact</span>
                  </div>
                  <div style="font-size:13px;color:var(--text-2);line-height:1.5;margin-top:2px">
                    Reason: <strong>${dec.reason}</strong>
                  </div>
                  <div style="font-size:11px;color:var(--text-3);margin-top:4px">
                    Approved by: ${dec.participants.join(', ')} • Linked Project: <strong style="color:var(--v-300)">${dec.project}</strong>
                  </div>
                </div>
              `).join('') : '<div style="font-size:12px;color:var(--text-3)">No decisions recorded.</div>'}
            </div>
          </div>

          <!-- Extracted Action Items Table -->
          <div class="dash-card">
            <div class="card-header-flex">
              <div class="card-title-group">
                <div class="ws-icon-box" style="background:rgba(34,197,94,0.15);color:#22c55e">⚡</div>
                <div>
                  <h2 class="card-title">Extracted Action Items (${mtg.actionItems ? mtg.actionItems.length : 0})</h2>
                  <div class="card-subtitle">Automatically converted into task commitments</div>
                </div>
              </div>
            </div>

            <div style="display:flex;flex-direction:column;gap:var(--s-3)">
              ${mtg.actionItems ? mtg.actionItems.map(act => `
                <div class="action-item-table-row">
                  <div style="flex:1">
                    <div style="font-weight:700;color:var(--text-1);font-size:14px">${act.title}</div>
                    <div style="font-size:12px;color:var(--text-3);margin-top:2px">Assigned to: <strong>${act.owner}</strong> • Due: ${act.dueDate}</div>
                  </div>
                  <button class="top-nav-btn primary-create" style="height:30px;font-size:11px" data-action="convert-task" data-action-id="${act.id}">
                    <span>${act.taskCreated ? '✓ Task Linked' : '+ Convert to Task'}</span>
                  </button>
                </div>
              `).join('') : '<div style="font-size:12px;color:var(--text-3)">No action items.</div>'}
            </div>
          </div>
        </div>

        <!-- Right Column (4 Cols): Recording & Chapters -->
        <div class="col-span-4" style="display:flex;flex-direction:column;gap:var(--s-6)">
          <div class="dash-card">
            <h3 style="font-size:var(--fs-md);font-weight:700;color:var(--text-1);margin-bottom:var(--s-3)">Meeting Recording</h3>
            <div style="height:140px;background:var(--bg-elevated);border-radius:var(--r-4);border:1px solid var(--border-1);display:flex;align-items:center;justify-content:center;font-size:32px;color:var(--v-400)">
              ▶
            </div>
            <div style="font-size:11px;color:var(--text-3);margin-top:8px">Duration: ${mtg.recording ? mtg.recording.duration : '44m 12s'}</div>

            ${mtg.recording ? `
              <div style="margin-top:var(--s-4)">
                <div style="font-size:11px;font-weight:700;color:var(--text-3);text-transform:uppercase;margin-bottom:6px">Chapters</div>
                <div style="display:flex;flex-direction:column;gap:4px">
                  ${mtg.recording.chapters.map(ch => `
                    <div style="font-size:12px;color:var(--text-2);padding:4px 6px;border-radius:4px;background:var(--bg-elevated)">
                      ${ch}
                    </div>
                  `).join('')}
                </div>
              </div>
            ` : ''}
          </div>
        </div>
      </div>
    </div>
  `;
}
